source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Spectra_Example', :exclusive => true do
  pod "Spectra", :path => "../"
end

target 'Spectra_Tests', :exclusive => true do
  pod "Spectra", :path => "../"

  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
end
